//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignMeUpMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOvertime
    {
        public int OvertimeId { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DateTimeStart { get; set; }
        public Nullable<System.DateTime> DateTimeEnd { get; set; }
        public Nullable<System.DateTime> SignUpEnd { get; set; }
        public Nullable<int> SelectedEmployeeId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
